### ISSUE TITLE
Feature request: Impl From<_> for AMQPValue

### ISSUE THREAD

**Issue by jerry73204** [sozu-proxy/amq-protocol#14] opened 2019-12-09 18:10 UTC
From my experience with laptin, it's pretty common to build headers of (String, AMQPValue) pairs that is sent with message. I found it cumbersome to write `AMQPValue::ShortInt(10)`. Suppose we can implement `From<_>` traits for common types, that we can simply write `10.into()`. That would give us a bit of convenience.

**Comment by Keruspe** [comment] 2019-12-09 18:24
The problem is that ShortInt and ShortShortInt are not the same, so what
would 10.into() return ? A ShortInt ? A LongUInt ?

**Comment by jerry73204** [comment] 2019-12-11 20:08
That's my misconduct. To elaborate, I would like to be able to call `From::from` whenever the input type is explicit. For example,
- from(x: u8) -> AMQPValue::ShortShortUInt(x)
- from(x: bool) -> AMQPValue::Boolean(x)
- from(x: Vec<u8)>) -> AMQPValue::ByteArray(x)

I see the little trouble to whether convert `String` to `ShortString` or `LongString`. Since `ShortString` is deprecated, I think `LongString` would be fine, or we can simply leave it untouched.

**Comment by Keruspe** [comment] 2020-02-25 17:40
Released as part of 4.2.0 which will ship with lapin 0.31

**Closed** 2020-02-25 17:41 UTC
